ADD FEEDBACK ADDITIONAL FIELDS
UKHSA-Internal/data-dashboard-frontend pull request #553
Opened 2024-11-25 13:29 UTC by Temiakinsoto

# Description
In wagtail there are a good number of field types supported that can be selected in the CMS. Currently for feedback we only use 'multiline' and 'radio' types. This PR implement other types, URL, EMAIL, NUMBER, DROPDOWN AND CHECKBOXES:

Fixes #CDD-2298

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [ ] Unit tests
- [ ] Playwright e2e tests
- [ ] Mobile responsiveness
- [ ] Accessibility (i.e. Lighthouse audit)
- [ ] Disabled JavaScript

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] Any styles in this change follow the 'STYLES.md' guide
- [ ] My changes are progressively enhanced with graceful degredagation for older browsers and non-JavaScript users
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

2024-11-25 22:23 UTC, rhys-burendo requested changes

2024-11-25 22:23 UTC, rhys-burendo commented on src/app/components/cms/Feedback/Feedback.tsx
> +      {fieldType === 'email' && <EmailField label={label} helpText={helpText} cleanName={cleanName} />}
Loving the pulling out of each of these to their own component. To the point where I'd like to request you do it to the other 3 existing fieldTypes please

2024-11-25 22:23 UTC, rhys-burendo commented on src/app/components/cms/Feedback/Feedback.tsx
> +        <CheckboxesField label={label} helpText={helpText} cleanName={cleanName} defaultValue={defaultValue} />
Just about got it here like the component, however we want to make sure we're mapping through each of the 'choicesList' constant, to have multiple checkboxes.

Then in this list, check whether each individual item matches the 'default value' (or values) and has the checkbox state equal to this

2024-11-25 22:23 UTC, rhys-burendo commented on src/app/components/cms/Feedback/Feedback.tsx
> +        <DropdownField label={label} helpText={helpText} cleanName={cleanName} choices={choices} />
We're passing in choices here, then creating the choices list inside the DropdownField component. To avoid repetition we can probably just pass through the choicesList prop from earlier in this component.

Alternatively to keep each component responsible for everything related to it, then pass through 'choices' to each (Dropdown, radio buttons & checkboxes)

2024-11-25 22:23 UTC, rhys-burendo commented on src/app/components/cms/Feedback/Feedback.tsx
> +      {fieldType === 'checkboxes' && (
We want to make sure we've got a fieldType option for both 'checkbox' and 'checkboxes'. I know its a bit odd, but those are the values returned from wagtail - it'll just be the same but a single item vs an array map

2024-11-25 22:23 UTC, rhys-burendo commented on src/app/components/cms/Feedback/Fields/Checkboxes/CheckboxesField.tsx
> +          {trimmedValuesList.map((defaultVal, key) => {
As discussed above this isn't quire right. Here you're looping through the default values. Whereas we want to be looping through the choices, and checking each choice against default values to see if it is 'default'

2024-11-29 10:05 UTC, rhys-burendo commented on src/app/components/cms/Feedback/Fields/Url/UrlField.tsx
> +      <input className="govuk-input" name={cleanName} id={cleanName} type="text" />
```suggestion
      <input className="govuk-input" name={cleanName} id={cleanName} type="url" />
```

2024-11-29 10:20 UTC, rhys-burendo commented on src/app/components/cms/Feedback/Feedback.tsx
>      </Fragment>
It's great we've got each of these separated out into individual components now, and each of those components is extensively tested. 
We'll probably also be looking for a little bit of feedback logic tests here, including:

- ChoicesList logic (Takes choices and splits on \r\n, splits on comma, splits as expected for both)
- defaultValuesLst logic (As above)
- That each fieldtype input matches to the correct output component
- Later on these tests will be expanded to include validation (but not part of this ticket)

2024-11-29 10:49 UTC, Temiakinsoto commented on src/app/components/cms/Feedback/Fields/Url/UrlField.tsx
> +      <input className="govuk-input" name={cleanName} id={cleanName} type="text" />
Nice spot. thanks

2024-11-29 11:38 UTC, Temiakinsoto commented on src/app/components/cms/Feedback/Fields/Checkbox/Checkboxfield.spec.tsx
> +    expect(helpText).toBeInTheDocument()
Done

2024-12-03 15:15 UTC, rhys-burendo approved these changes

2024-12-19 11:27 UTC, luketowell approved these changes
Tested locally and reviewed recent commits

2024-12-20 08:23 UTC, merged